COMMAND_DOESNT_EXIST_ERROR_CODE = 1
INVALID_ARGUMENTS_ERROR_CODE = 2
INSERT_REMOVE_INDEX_OUT_OF_BOUNDS_ERROR_CODE = 3
CANNOT_DISPLAY_BLANK_ERROR_CODE = 4
CANNOT_UNDO_ANYMORE_ERROR = 9

INDEX_OF_FIRST_PROBLEM_SCORE = 0
INDEX_OF_SECOND_PROBLEM_SCORE = 1
INDEX_OF_THIRD_PROBLEM_SCORE = 2
INDEX_OF_CONTESTANT_POSITION = 3

IMPOSSIBLE_SCORE = -1
